name: check-prettier
run-name: Check code formatting
on: [push, pull_request]
jobs:
  check-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm install
      - name: Check formatting
        run: npx prettier . --check
